"""
Django settings for arabella project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# ✅ أضفناه: لاستخدام DATABASE_URL (Postgres) عند توفره على Render
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ✅ أضفناه: مسار ثابت للبيانات على Render (Persistent Disk) + افتراضي /var/data


# ✅ أضفناه: إنشاء مجلد الداتا إن لم يكن موجودًا (مهم لـ SQLite/Media)
# ✅ DATA_DIR على Render (Persistent Disk) — قد يكون غير قابل للكتابة وقت الـ Build
#DATA_DIR = Path(os.getenv("DATA_DIR", "/var/data"))
DATA_DIR = Path(os.getenv("DATA_DIR", "/var/data"))


# ✅ أنشئ المجلد فقط إذا كان قابل للكتابة (وما تكسر الـ build)
try:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
except OSError:
    # إذا /var/data read-only (وقت build) تجاهله
    pass



# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "change-me")

# ✅ عدّلناه: قراءة DEBUG من ENV بشكل واضح (true/false)
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

# ✅ أضفناه: Render يوفّر اسم الدومين الخارجي تلقائيًا
RENDER_EXTERNAL_HOSTNAME = os.getenv("RENDER_EXTERNAL_HOSTNAME", "").strip()

# ✅ عدّلناه: إعداد ALLOWED_HOSTS بشكل آمن + مناسب لـ Render + يمنع كراش إذا ENV فاضي
if DEBUG:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
else:
    # ✅ أضفناه: قراءة ALLOWED_HOSTS من ENV بصيغة مفصولة بفواصل
    env_hosts = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "").split(",") if h.strip()]
    ALLOWED_HOSTS = env_hosts

    # ✅ أضفناه: إضافة دومين Render تلقائيًا حتى لو نسيت تعبي ALLOWED_HOSTS
    if RENDER_EXTERNAL_HOSTNAME:
        ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

    # ✅ أضفناه: السماح لطلبات health-check الداخلية (localhost / 127.0.0.1)
    ALLOWED_HOSTS += ["localhost", "127.0.0.1"]

    # ✅ أضفناه: fallback نهائي إذا بقيت القائمة فاضية لأي سبب
    if not ALLOWED_HOSTS:
        ALLOWED_HOSTS = ["arabillacaffe.onrender.com", "localhost", "127.0.0.1"]

# ✅ أضفناه: Render خلف Proxy، فخلّي Django يحترم X-Forwarded headers
USE_X_FORWARDED_HOST = True

# ✅ أضفناه: حتى Django يعرف إن الطلب HTTPS خلف البروكسي
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "menu",
]

# ✅ عدّلناه: ترتيب WhiteNoise لازم يكون مباشرة بعد SecurityMiddleware
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # ✅ عدّلناه (نقلناه): WhiteNoise مباشرة بعد SecurityMiddleware
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "arabella.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # مجلد templates العام
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "arabella.wsgi.application"


# Database

# ✅ أضفناه: اقرأ DATABASE_URL إن وجد (Postgres على Render) وإلا ارجع لـ SQLite على الديسك الدائم
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()

# ✅ أضفناه: إذا يوجد DATABASE_URL استخدمه
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
# ✅ أضفناه: وإلا استخدم SQLite على الـ Persistent Disk
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            # ✅ عدّلناه: SQLite على DATA_DIR (مو BASE_DIR) حتى ما تضيع مع كل deploy
            "NAME": str(DATA_DIR / "db.sqlite3"),
        }
    }


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization

LANGUAGE_CODE = "ar"
TIME_ZONE = "Asia/Damascus"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# ✅ عدّلناه: استخدام STORAGES (الطريقة الحديثة) بدل STATICFILES_STORAGE
STORAGES = {
    # ✅ أضفناه: WhiteNoise storage مع manifest (أفضل للإنتاج)
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
}

# ✅ أضفناه: أحيانًا يفيد في حالات معينة مع Django/WhiteNoise (اختياري لكنه آمن)
WHITENOISE_AUTOREFRESH = DEBUG


# Media

MEDIA_URL = "/media/"

# ✅ عدّلناه: MEDIA على الديسك الدائم (مو ضمن المشروع)

# ✅ أضفناه: إنشاء مجلد media على الديسك الدائم
MEDIA_ROOT = str(DATA_DIR / "media")

# ✅ أنشئ مجلد media فقط إذا أمكن (بدون كسر الـ build)
try:
    Path(MEDIA_ROOT).mkdir(parents=True, exist_ok=True)
except OSError:
    pass



# ✅ أضفناه: CSRF trusted origins لتسجيل دخول admin عبر https على Render
CSRF_TRUSTED_ORIGINS = [
    "https://arabillacaffe.onrender.com",
]

# ✅ أضفناه: Logging بسيط حتى يظهر سبب 500 في logs عندما DEBUG=False (مفيد للتشخيص)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {
        "django.request": {"handlers": ["console"], "level": "ERROR", "propagate": False},
        "django": {"handlers": ["console"], "level": "INFO"},
    },
}


# Default primary key field type

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
